# Generated by Django 5.1.1 on 2024-10-09 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_task_shared_with"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="shared_with",
            new_name="shared_with_users",
        ),
    ]
