# Generated by Django 5.1.1 on 2024-10-09 09:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_rename_shared_with_task_shared_with_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="shared_with_users",
        ),
    ]
